### ISSUE TITLE
Iter Infusion & Missing Text

### ISSUE THREAD

**Issue by LazerusKI** [TheDrunkMafia/ThaumicInfusion#10]
http://pastebin.com/jvNsuAh8

The Iter Infusion caused a World Crash.

After Placing them, i wnated to figure out how they work.
I Clicked one placed block with another one,
The clicked block turned into an Obsidian Totem,
Everything nearby was swirling around it
Crash

Also Infernal and Superbia have no real text in the book

**Comment by TheDrunkMafia** [comment]
Thats an interesting crash... but iter has been re-coded and it more stable with the new block system. So this crash should never happen again.
