### ISSUE TITLE
Infusion Focus recipe has the wrong output

### ISSUE THREAD

**Issue by EXTER7** [TheDrunkMafia/ThaumicInfusion#12]
The recipe for the Infusion Focus makes a Warding Focus instead of an Infusion Focus.

![screenshot-1](https://cloud.githubusercontent.com/assets/3077881/7508459/827ea5c6-f44e-11e4-99c9-89a6251decd2.png)

**Comment by TheDrunkMafia** [comment]
Thanks, I'm about to release a hotfix for the recipe. https://github.com/TheDrunkMafia/ThaumicInfusion/blob/da370c049296c4e89acb9fab6bb36b3fc6d016e6/src/main/java/drunkmafia/thaumicinfusion/common/intergration/ThaumcraftIntergration.java#L60
