### ISSUE TITLE
Infusion Focus

### ISSUE THREAD

**Issue by Sohala123** [TheDrunkMafia/ThaumicInfusion#13]
The recipe listed in the thaumonomicon functions, but just makes another Wand Focus: Warding

**Comment by TheDrunkMafia** [comment]
Thanks, I'm about to release a hotfix for the recipe. https://github.com/TheDrunkMafia/ThaumicInfusion/blob/da370c049296c4e89acb9fab6bb36b3fc6d016e6/src/main/java/drunkmafia/thaumicinfusion/common/intergration/ThaumcraftIntergration.java#L60
