### ISSUE TITLE
Thaumonomicon Entrys not Complete

### ISSUE THREAD

**Issue by LazerusKI** [TheDrunkMafia/ThaumicInfusion#14]
Just started two different maps.
The first map showed the entry for Aqua Infusion (should turn a block into a disguised water block, right?)
The second map didnt.
Also the Order i which they were listed were different.
Alphabetical sorting would be better here if possible

**Comment by TheDrunkMafia** [comment]
Possible yes, they appear different because the list they are added to does not retain its order that they were placed in. So each time they are accessed it is random in what comes out first.

**Comment by LazerusKI** [comment]
Wanted to test if the Transfer Node from Extra Utilities with World interaction upgrades can collect water from such a block. Sadly it cant, thats why i was a bit confused when the entry was gone^^

**Comment by TheDrunkMafia** [comment]
Oh, yeah the aqua block has been esspically coded to act like water but NOT be water. So you cant pick it up with buckets nor will it be compatible with pumps from bc.

**Comment by LazerusKI** [comment]
So basically like...what was it called...Xychorium? Water nearby fields, turn Lava into Cobble etc.
Would be interesting if it could fill Inventories who are in the field of it, like Tanks or Machines.
