### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by LazerusKI** [TheDrunkMafia/ThaumicInfusion#15]
After reading the Thaumonimicon Entry, i noticed that the game began to stutter and lag.
I had the same problem a while ago with Thamic Horizons and Travelers Gear, so i knew one of my new updates was causing it. Minechem and TI were updated, and after removint Thaumic Infusion, the leak was gone, no more stuttering and lagging

**Comment by TheDrunkMafia** [comment]
Its not a memory leak, the research is currenty generated at runtime. I'll make change it to calculate the localizations in the next update.

**Comment by LazerusKI** [comment]
False alarm i think.
Started to stutter again, searching for the cause now
