### ISSUE TITLE
Recommendation: Fabrico infusion.

### ISSUE THREAD

**Issue by VoilaTada** [TheDrunkMafia/ThaumicInfusion#16]
Not sure if this is planned or not, but I think that infusing a block with Fabrico should make the block function as either a vanilla or arcane crafting table.

**Comment by TheDrunkMafia** [comment]
Hmmm, the way I tried to do the effects is make them add open ended functionality that allows the players to do build things with them. Making something open a GUI would be cool, but it would not suit the rest of the effects. Though that does not mean its a bad idea, I just dont see it fitting with the theme of the mod.

**Comment by VoilaTada** [comment]
Ah I see, thanks for the reply. :D
