### ISSUE TITLE
Spiritus Infusion: Slightly broken

### ISSUE THREAD

**Issue by LazerusKI** [TheDrunkMafia/ThaumicInfusion#19]
Blocks with this Infusion (im talking about the Focus version) are slightly broken.
Walking through them works, but they act like flowing water, they try to push you out.
Oddly enough, this only happens in one direction, the other ways work smothly, just one of them pushes you out.

**Comment by TheDrunkMafia** [comment]
Thats an easy fix, its because I don't actually set the block to not solid so its treated as a block.

**Comment by TheDrunkMafia** [comment]
Spiritus has been fixed, it will be released in the next update which will be coming out by the end of next week or alternative you can build yourself a copy from the repo.
