### ISSUE TITLE
Focal Manipulator

### ISSUE THREAD

**Issue by LazerusKI** [TheDrunkMafia/ThaumicInfusion#20]
Dont know if you forgot it, or if you have left it out on purpose.
anyway, the focus cant be upgraded.

Since it mimics the warding focus in most aspects, would it be possible to mimic the upgrades too?
especially enlarge and architect might be handy

**Comment by TheDrunkMafia** [comment]
I know, upgrades are planned, but for now I am focusing on fixing any issues that people are having with the infusion system. One its all stable I will add some upgrades
