### ISSUE TITLE
Issue with Malisis doors

### ISSUE THREAD

**Issue by lordstarfox** [TheDrunkMafia/ThaumicInfusion#21]
Minecraft Forge 10.13.3.1403
malisisdoors-1.7.10-1.7.1.jar
malisiscore-1.7.10-0.11.4
Thaumic Infusion:4.002
Thaumcraft-1.7.10-4.2.3.5.jar

Crashing with the following crash report when trying to put blocks into Vanishing Frames(diamond Vanishing Frame specifically): http://pastebin.com/XRwzS5Pz
Doesn't happen with Thaumic Infusion removed. Wasn't happening with ThaumicInfusion-3.966 (i did update Forge after updating to 4.x)
Let me know if you need more info (or if this should go to Malisis Github).

**Comment by TheDrunkMafia** [comment]
I'll try and recreate the crash in my Environment as the line it is pointing to has changed sing the build you are using,

**Comment by TheDrunkMafia** [comment]
This is an issue with Malisis doors, they are referencing something which is null when my mod converts the blockAccess to a world object to get the associated data.

**Comment by TheDrunkMafia** [comment]
I've posted an issue on their repo telling them what the issue is and the cause. This issue will make their mod crash any mod that attempts to call a certain method.

**Comment by lordstarfox** [comment]
Alright,thank you for taking your time to check and report it.
