### ISSUE TITLE
[Enhancement] Transparent Aspect Icon on Infused Location

### ISSUE THREAD

**Issue by Alaberti** [TheDrunkMafia/ThaumicInfusion#26]
Just a thought, it might be useful to have infused locations display an icon of the aspect(s) they are infused with. Perhaps as a focal upgrade, maybe default,  and/or with a config option to adjust functionality maybe?

**Comment by TheDrunkMafia** [comment]
That is in the works, I however am busy at the moment with other things going on. This will be implemented in the update after the performance fix.
