### ISSUE TITLE
Crash On New World Load

### ISSUE THREAD

**Issue by vech2514** [TheDrunkMafia/ThaumicInfusion#27]
With the new version of TI, the latest version of thaumcraft, the latest forge, and the latest version of mystcraft an OutOfBoundsException occurs once a new world is created which causes a crash to desktop. From what can be seen it would seem as though the error is associated with Thaumic Infusion attempting to access world data in the mystcraft empty dimension -2147483648. 

The crash log can be found here: http://pastebin.com/VLbmDA3c

**Comment by TheDrunkMafia** [comment]
I see the issue, though this crash should never of happened because the code should resize the arrays to suit the data. I'll release a hotfix shortley

**Comment by TheDrunkMafia** [comment]
This should fix the issue: https://github.com/TheDrunkMafia/ThaumicInfusion/commit/acc927aa23b0a147f6a7604829bb48bbcf5d731c

**Comment by TheDrunkMafia** [comment]
The issue seems to be fixed, but why the dimension ID is that big I have no idea. My array system was not built to handle numbers of that size.

**Comment by vech2514** [comment]
It is weird, I was convinced at first that that number was out of bounds of how large a negative number could be on my computer. It looks to me though that maybe mystcraft uses that as a dummy age of a sorts... which would explain why its such an out of the way age. Thanks for addressing the problem so quickly!

**Comment by TheDrunkMafia** [comment]
Here you go: http://minecraft.curseforge.com/mc-mods/220308-thaumic-infusion/files/2242095 - Its fixed
