### ISSUE TITLE
Any block duplication from Wither Boss attempting to break spaces infused with Humanus

### ISSUE THREAD

**Issue by dirtyfargo** [TheDrunkMafia/ThaumicInfusion#28]
When the Wither Boss attempts to break these blocks in spaces that have been Thaumically Infused with Humanus, it duplicates the block as an item drop while leaving the placed version undamaged. Demonstration of this can be seen in the short unlisted Youtube video linked below.

https://youtu.be/Y2F-LYNY_30

This is on a server, and in a modpack, have not tested in single player or stand-alone yet.
Forge Version: 10.13.4.1470
Thaumcraft: 4.2.3.5
Thaumic Infusion: 4.07

**Comment by TheDrunkMafia** [comment]
Easy fix, I have to release a hotfix to deal with blocks disappearing and a recipe issue. I'll do it for then

**Comment by TheDrunkMafia** [comment]
This issue has now been fixed: https://github.com/TheDrunkMafia/ThaumicInfusion/commit/7f84f224f1c7be42710fc1427a49e4309e4977bd

I'll release the hot fix soon.

**Comment by dirtyfargo** [comment]
Awesome, thank you :)
