### ISSUE TITLE
Impossible Aspect Block recipes

### ISSUE THREAD

**Issue by Zsashas** [TheDrunkMafia/ThaumicInfusion#29]
I realized finally that the aspect blocks are supposed to be made of four of the specific Ethereal Essences for that aspect. However, it somehow got mixed up and now requires Alumentum attuned to the aspects, which is completely impossible. I posted it on the forum thread but I don't know how often that is checked.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1445452-tc-add-on-thaumic-infusion-4-05-new-version?comment=538

Also, please add a config option to use left click with the focus to bind blocks. I can't get whatever way it currently is to work.

**Comment by TheDrunkMafia** [comment]
I've fixed out the Recipes and it will be coming out in the hotfix soon, along the lines of linking. Right click a two blocks with an empty wand should link the effects, I have a better way to do this in the works but it is going to be for 1.8.
