### ISSUE TITLE
[Crash] Placing infused block on forge multiplayer server (not Cauldron).

### ISSUE THREAD

**Issue by MCShammer** [TheDrunkMafia/ThaumicInfusion#3]
Created my 1st infusion block using spiritus hoping to make a secret passageway.

When placed in the world the server crashed.

http://pastebin.com/ATyqZ8cQ

When the server is restarted, I have a textureless block(Clear?) that is solid and unable to be walked through.
I am unable to break it in survival mode, but I am in creative. Also it can be picked up using Thaumic Tinkerer's Dislocation focus, but the server crashes if placed back down. Please see the screenshot.

http://i.imgur.com/bEPAozU.png

Is there anything else I can provide that will be helpful?

p.s. Tried using a different infused aspect as well, Potentia also crashes the server and does not act like a redstone block.

**Comment by TheDrunkMafia** [comment]
That is an interesting issue, I've fixed that crash from happening. But it would seem that another mod is firing some methods with a null world server side, causing the server to bypass the checks to grab the server world obj and eventually making it attempt to grab it from a client method.

The block is clear because it can't access it's data.

**Comment by MCShammer** [comment]
Well after your explanation of what was going on, I found the culprit.

Fastcraft.
(The semi-magical server/client mod that helps speed the game up)
forum.industrial-craft.net/index.php?page=Thread&threadID=10820

When I remove the Fastcraft mod from the server, it no longer crashes when I place the infused blocks in the world.

I am still running Fastcraft on the client side.

Something odd that still happens, and its not a Huge deal just thought I'd mention it, but if you use the pickblock key (middle mouse button for me) on an infused block in creative mode it will place the same invisible block as before, but will not crash the server.

http://i.imgur.com/E6rmJN2.png

Unknown how much farther you want to take this info, as fastcraft can be quite useful for folks.

For now I will simply run the server without Fastcraft. 

Thank you for your help and thank you for your awesome Mod!
