### ISSUE TITLE
Incompatibility with Forge Essentials

### ISSUE THREAD

**Issue by Sunconure11** [TheDrunkMafia/ThaumicInfusion#30]
This mod does not work with Forge Essentials.

http://pastebin.com/an1pB2Q4

**Comment by TheDrunkMafia** [comment]
Simple fix, Essentials is triggering the event and providing a null object within the event. Will be fixed next commit.

**Comment by TheDrunkMafia** [comment]
This has now been resolved, the fix will be released along with the new version for 1.7.10.
