### ISSUE TITLE
Opening infusion menu crash.

### ISSUE THREAD

**Issue by Gorgok** [TheDrunkMafia/ThaumicInfusion#32]
Not sure if this crash is something compat related, as there are some extra aspects in my set of mods. It technically opens, graphics appear, then client crashes. Server is unaffected.

This is with 4.14.

http://pastebin.com/sszzWVPt

**Comment by TheDrunkMafia** [comment]
Interesting, this is the first crash for the GUI. I'll implement a fix and release the hotfix later today.

**Comment by TheDrunkMafia** [comment]
If you don't mind testing, I can send you a build with the supposedly fix to ensure that it is working before releasing the hotfix?

**Comment by TheDrunkMafia** [comment]
This issue has been resolved with the latest release on curse forge, if it persists reopen this issue and I will look at it again.
