### ISSUE TITLE
Crash when looking through creative inv

### ISSUE THREAD

**Issue by CrowBBGN** [TheDrunkMafia/ThaumicInfusion#34]
I was checking out all the pretty blocks and such in the creative menu and crash...

http://pastebin.com/mR5jJQJj

**Comment by TheDrunkMafia** [comment]
Thermal Dynamics is causing this crash, however I will implement some null checks in the method. Even though the parameters shouldn't be null anyway. More than likely they are passing in a wrapped IBlockAccess.

**Comment by TheDrunkMafia** [comment]
Has been fixed in the latest version that has been uploaded to the Curse Forge, if the problems persists. Then please reopen this issue.
