### ISSUE TITLE
Crash after updating to 4.19

### ISSUE THREAD

**Issue by LazerusKI** [TheDrunkMafia/ThaumicInfusion#36]
http://pastebin.com/LVe8pEtk

4.18 still works

**Comment by EdC94** [comment]
same crash, only on server, not on single player

**Comment by Amaxter** [comment]
I too can confirm
http://hastebin.com/utojomahix.1c

**Comment by TheDrunkMafia** [comment]
Yeah, In my haste to release a version before I got on the plane. I managed to miss a side check, which has now been resolved. I'm currently working on another issue, which is the thermal dynamics crash. I will release a hotfix as soon as I am not suffering from jet-lag.

**Comment by Amaxter** [comment]
Ok, no worries. Get some rest :)

**Comment by LazerusKI** [comment]
Jup, as long as the previous version works, its no big deal ;)

**Comment by TheDrunkMafia** [comment]
Uploaded a new version of the mod on the curseforge. May take a while for it to be accepted, however when it's up if you find any issues please post it on here & I will do my best to fix it.

**Comment by Amaxter** [comment]
Awesome :)
