### ISSUE TITLE
Visual Effect is vanishing

### ISSUE THREAD

**Issue by LazerusKI** [TheDrunkMafia/ThaumicInfusion#39]
Just trolled a friend with the Alienis infusion and noticed, that the visual effect vanished after a while.

I dont know exactly what caused it, i switched foci a few times, and at some point the effect was simply invisible.
i could still interact with it, i could infuse the block again to remove the effect. i could also readd the effect to make it visible again.

**Comment by TheDrunkMafia** [comment]
Hey Man, try this version: https://dl.dropboxusercontent.com/u/101919880/Thaumic%20Infusion/ThaumicInfusion-4.22.jar

I am still currently abroad, so I am unable to effectively test the issues you have brought up. The changes related to this issue are as follows:
Data Structure has been reworked for optimization,
Data Rendering more streamline & more intelligent in how it obtains the chunks for rendering.

Don't know if this will fix the issue, if it doesn't then it is going to have to wait till I am able to fully test the code on my desktop.

**Comment by LazerusKI** [comment]
It doesnt ;)
Tried it this time with the spiritus infusion for a secret door, logged of for a few hours, and when i came back the effect was gone - needed to remove and ifuse it again to walk through it again.

**Comment by TheDrunkMafia** [comment]
I've looked into the syncing of effects while on a server & saw the issue with chunk loading, I've rewritten it to send any missing blocks to the player if the block count differs.

**Comment by LazerusKI** [comment]
Its still there, i can infuse blocks, teleport away, teleport back, and all the infusions are gone until i replace them twice (remove and set again)

**Comment by TheDrunkMafia** [comment]
Interesting, I will revist the chunk loading to see if it is a rendering issue or the client secretly unloads the blocks & then reloads without firing the event that drives TI's data loading.

**Comment by LazerusKI** [comment]
rendering issue would be weird, because the whole effect is gone.
spiritus made the wall solid again, alienis removed the teleports, so it sounds like it unloads them but doesnt load them again

**Comment by TheDrunkMafia** [comment]
I've fixed this, I traced it back to a packet that the client sends to the server to request that data from specific chunks be sent to the client for loading. I will release it soon, since 1.8 was a dead end as Azanor is not really working on it.

**Comment by LazerusKI** [comment]
yeah, i heard that many mod-devs are skipping 1.8, but nice that you found the issue :)

**Comment by Zsashas** [comment]
Actually, apparently Azanor IS working on 1.8 still. But 1.7.10 is still the main version for now.

**Comment by TheDrunkMafia** [comment]
Yeah, I know he's working on a 1.8 version. However the developer version he has given out is nowhere near complete enough to be able to properly update Thaumic Infusion to 1.8, I've updated all the Forge/Minecraft changes, but everything that works with Thaumcraft will have to wait.
