### ISSUE TITLE
Potentia infused blocks not acting like a redstone block

### ISSUE THREAD

**Issue by MCShammer** [TheDrunkMafia/ThaumicInfusion#4]
Infused an oak plank with potentia hoping to have a hidden source of redstone power, Infused block does not seem to emit power.

http://i.imgur.com/gHXQUfs.png (Showing the infusion)
http://i.imgur.com/U19jzKf.png (Showing the lack of power)

The other infusions I have tried have worked great so far!

(Tested without Fastcraft on my client in case it was interfering as well)

using version 3.83 in minecraft version 1.7.10 Forge modded client.

**Comment by TheDrunkMafia** [comment]
It's weird how potentia works, instead of giving off a red stone signal it makes touching blocks give it off. I need redo most effects and polish them up, but I have not had a chance yet as I've been making heavy changes to the internal infusion system.

**Comment by MCShammer** [comment]
Ah! I was just using it wrong, thank you for the reply!
