### ISSUE TITLE
Perditio Effect renders different on Servers (+ suggestion)

### ISSUE THREAD

**Issue by LazerusKI** [TheDrunkMafia/ThaumicInfusion#40]
I had infused the top of a tree with it, to test how it works.
a fried hit the block then, destroyed it and caused the explosion.

for me the whole tree was gone.
for him it was just that one block.
the hitbox of those "invisible blocks" was still there, and after relogging i could see them again

also a suggestion for this one:
would be good when the explosion would remove the infusion, so that you need to readd it to let it explode again (basically a one-use infusion)

**Comment by TheDrunkMafia** [comment]
Hey Man, try this version: https://dl.dropboxusercontent.com/u/101919880/Thaumic%20Infusion/ThaumicInfusion-4.22.jar

I am still currently abroad, so I am unable to effectively test the issues you have brought up. The changes related to this issue are as follows:
Fixed client side calculating explosion & not server,
Perdito is now removed when exploded.

**Comment by LazerusKI** [comment]
Just tested, now Perditio doesnt explode at all.
Also the effect is not removed, instead it is "locked", cant remove it with a simple rightclick, instead i have to shift-rightclick it

**Comment by TheDrunkMafia** [comment]
The final 1.7.10 update, should fix the issues you've come across with Perditio.
