### ISSUE TITLE
Lux update problem and save/lost problem

### ISSUE THREAD

**Issue by adamsonich** [TheDrunkMafia/ThaumicInfusion#42]
I found this post https://github.com/TheDrunkMafia/ThaumicInfusion/issues/23#event-335593684
Can autor review bug? Maybe on fresh head it will be fixed?

**Comment by TheDrunkMafia** [comment]
I've just fixed this bug, It was an issue within the initial packet that is sent from the client requesting the chunks to be sent.

**Comment by adamsonich** [comment]
when U release compiled version?

**Comment by TheDrunkMafia** [comment]
http://www.curse.com/mc-mods/minecraft/220308-thaumic-infusion Latest version has been uploaded to curse
