### ISSUE TITLE
Mod interaction crash

### ISSUE THREAD

**Issue by Zsashas** [TheDrunkMafia/ThaumicInfusion#51]
Ok so it seems that three mods are involved with this.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2350259-deeper-caves-go-beyond-the-void-alpha-4000

Using the deeper caves mod, I had just dropped down into the first cave level, when it crashed. Some sort of interaction between TI and Reika's GeoStrata.

http://hastebin.com/likogeqito.coffee

**Comment by TheDrunkMafia** [comment]
It will be on my side, I've not touched my mods code in a while but I know what to do to fix this.

However two questions, does this occur without Ti and are any blocks in the world infused?

**Comment by Zsashas** [comment]
No and no.

**Comment by TheDrunkMafia** [comment]
Unfortunately this is for 1.7.10, I've moved over to 1.8 since then. I've been away from working on TI for too long, so I will complete the 1.8 version and I will introduce a fix to ensure that this wont happen again.
