### ISSUE TITLE
Server CPU usage remains at 100% when ThaumicInfusion is installed

### ISSUE THREAD

**Issue by ajthemacboy** [TheDrunkMafia/ThaumicInfusion#52]
Recently, I've been having performance problems on my server. Even when 0 players are online, and the whole server ticktime is less than 2 milliseconds, CPU usage on my server remains at max (200%, 100% on each core.)

After extensive testing I have found this to occur because of two mods; Peripherals++ and ThaumicInfusion. Note that this is NOT an issue with comparability between these two mods. If I remove ThaumicInfusion, Peripherals++ takes up 200% usage, and vice versa with ThaumicInfusion. 

This occurs with normal Forge, and with Cauldron. 

Please let me know if you need more info!

**Comment by TheDrunkMafia** [comment]
The only thing that can be causes high CPU usage is the aspect stabilizer, which is a WIP feature that has been implemented in the public builds. You can turn it off in the config, if that does not fix the high overhead, then it won't be Thaumic Infusion. The only time TI will cause performance issues if the is a ridiculous amount of ticking infusions in the same area.

**Comment by ajthemacboy** [comment]
Disabling the Aspect Stabilizer fixed the constant 200% usage. This is obviously an issue though, as it's enabled by default and apparently runs CONSTANTLY, even in brand new worlds.

**Comment by TheDrunkMafia** [comment]
Its not enabled by default anymore in the 1.8 released.

**Comment by ajthemacboy** [comment]
But when it is enabled it causes lag. One solution is to make it optional, but the other solution is to optimize it.

**Comment by TheDrunkMafia** [comment]
The stabilizer is a WIP feature, that is optional. It was enabled by default in one of the releases for 1.7, but can still be toggled in the config. It will be getting removed all together soon anyway, due to people thinking that the mod was already costly to begin with and does not need to be balanced.
