### ISSUE TITLE
Infusions Cease Working after a short period of time

### ISSUE THREAD

**Issue by Alaberti** [TheDrunkMafia/ThaumicInfusion#53]
Long time no talk! Hope the holidays are treating you well.

Found a bit of an interesting problem with every infusion.  1.7.10, TI version 4.3, forge 1566. The effects, and the glowy box, all end after about a minute or two. Tested on every aspect. It's like they forgot they were infused. Not sure how I didn't notice before.

**Comment by TheDrunkMafia** [comment]
In the 1.7.10 Version there is a WiP feature which requires the aspects to be fueled by nearby jars, to disable it go into the config and change aspect stabilizer to false.

**Comment by Math321** [comment]
Lux, Praecantatio, and Ignis do not appear to need fuel. Intentional?

**Comment by TheDrunkMafia** [comment]
Indeed, Cosmetic items do not need to be fueled. However the feature has been made redundant as in testing it seemed overkill. The mod is already expensive as is.

**Comment by Math321** [comment]
Fabrico is cosmetic, yet decays if not fueled, just to point that out.

I do not see a way to disable the Essentia drain in the config, unless that's in the most recent version for 1.7.10?
