### ISSUE TITLE
No background in the 1.7.10 build's tab

### ISSUE THREAD

**Issue by Sunconure11** [TheDrunkMafia/ThaumicInfusion#55]
https://www.dropbox.com/s/yzyy6qk2mrae00t/Screenshot%202016-01-14%2015.34.49.png?dl=0

You might want to release a hotfix for this, even though you are moving to 1.8.

**Comment by TheDrunkMafia** [comment]
Yeah, I've done it. The build did not include the background image, I've uploaded it to curse. Just waiting for it to be processed.
