### ISSUE TITLE
Random crashes while digging gravel.

### ISSUE THREAD

**Issue by sdaddy** [TheDrunkMafia/ThaumicInfusion#56]
http://hastebin.com/raw/oyezavazot

This is a relatively new world and I haven't even begun in Thaumcraft, so I have yet to touch Thaumic Infusion.

**Comment by sdaddy** [comment]
After checking the crash report again, it seems it may be CraftingTable IV's library, ElecCore, to blame. I'll report to it's mod author as well.

**Comment by sdaddy** [comment]
So I disabled both ElecCore and CraftingTable IV and still get the crash: http://hastebin.com/raw/juxegayusa

**Comment by TheDrunkMafia** [comment]
Yeah, this crash is occurring from within TI's Code. However the issue seems to be coming from the block class passing in null parameters, I will add in the needed null checks and do a build.

**Comment by TheDrunkMafia** [comment]
I have fixed the issue with the following build: http://minecraft.curseforge.com/projects/thaumic-infusion/files/2275598
