### ISSUE TITLE
Ticking entity crash.

### ISSUE THREAD

**Issue by Avalonzo** [TheDrunkMafia/ThaumicInfusion#57]
Hello I just installed the fixed version and every time I tried loading my world I would crash out to launcher here is the crash-report via pastebin http://pastebin.com/npEDCqku

**Comment by TheDrunkMafia** [comment]
Sorry about that, its fixed in this version: http://minecraft.curseforge.com/projects/thaumic-infusion/files/2275617

**Comment by Avalonzo** [comment]
No problem and thank you for your awesome mod also keep up the great work.
