### ISSUE TITLE
[1.8] 4.73 Ticking Entity Crash when creeper explodes

### ISSUE THREAD

**Issue by DrasticDemise** [TheDrunkMafia/ThaumicInfusion#58]
http://pastebin.com/MrRUQbAg

I got a CTD when a creeper simply exploded near me, fairly interesting crash which references Thaumic Infusion. Not really sure what happened.

Edit: The most out of place thing that I could point to was that it blew up a few order shards, but there is nothing else I can suspect from that.

**Comment by TheDrunkMafia** [comment]
This crash has already been fixed, you need to update to the latest version on the curse forge. http://minecraft.curseforge.com/projects/thaumic-infusion/files/2275617
