### ISSUE TITLE
Old issue? Infusions vanish again

### ISSUE THREAD

**Issue by LazerusKI** [TheDrunkMafia/ThaumicInfusion#60]
Just noticed that, the Spiritus infusion is vanishing (dont know if its still or again, since i have not played for a while).

When i leave the chunk where the infusion is in (teleport for example) and come back, the infusion is completely gone. Not like it was before where i had to remove the now invisible infusion and apply it again, this time it is completely gone like it never existed.

Also Perditio is still broken, when i tested it, it had no effect at all

**Comment by TheDrunkMafia** [comment]
Interesting, I will look into this. Is this in the single player world or on a server, also which version of the mod are you running and which version of MC are you playing in?

**Comment by LazerusKI** [comment]
Noticed it in the last "non hotfix" version, just updted to the latest hotfix and testing it there again.

world is on my server, running 24/7, MC version is 1.7.10

**Comment by TheDrunkMafia** [comment]
i'll look into Predito not working, but if everything is all good now. Then thanks for your help with fixing this bug.
