### ISSUE TITLE
1.8 rendering falling gravel

### ISSUE THREAD

**Issue by TheCricket** [TheDrunkMafia/ThaumicInfusion#61]
Using the latest FTB Unstable 1.8 as we are testing it
http://pastebin.com/dyAiWgtZ

**Comment by Zsashas** [comment]
Already reported several times, and those issues have all been closed by the look of it. Hopefully that means it was fixed c:

**Comment by TheDrunkMafia** [comment]
Yeah, this bug has been resolved in 1.8.9. However I will release a hotfix for 1.8.

**Comment by TheDrunkMafia** [comment]
Hotfix: http://minecraft.curseforge.com/projects/thaumic-infusion/files/2276041
