### ISSUE TITLE
1.8.9 Motus Void World

### ISSUE THREAD

**Issue by JoeSchmo2840** [TheDrunkMafia/ThaumicInfusion#66]
Testing with Forge 1.8.9-11.15.1.1724, Thaumcraft-1.8.9-5.1.4 and ThaumicInfusion-1.8.9-4.76.

I have infused a block (yellow wool) in the overworld. Clicked it with paper and began linking. Created an end portal. Entered the end. Immediately placed and Infused another block (yellow wool) and clicked it with the linking page and they successfully linked. It seems to work fine if I go Overworld->The End, but when I go The End->Overworld I get teleported to what looks like a void world. I can hear mobs, I can somewhat "find" the ground, but I cannot place blocks and if I try to break the invisible world nothing happens.

Note 1: This is with ONLY forge, thaumcraft and thaumic infusion on the client in a single player world. I have also had the problem on my test server running the same forge with sponge and lots of mods.

Note 2: I find save and quitting and then reloading the single player world puts you back at the Overworld's spawn. Reconnecting to the server does the same. In single player however the block (yellow wool) in The End has disappeared and the block (yellow wool) in the Overworld is unlinked after the save and quit. Going back and forth from 

Note 3: The Nether seems to be working just fine.

**Comment by TheDrunkMafia** [comment]
This is an interesting bug... I never actually tested the End, only the nether. I will look into this and if I find the cause of the issue, I will release the fix in the update I am sending out tomorrow.

This might have something to do with how I handle the dimension ID's and you could possibly be getting sent to new dimension, do you mind doing a test were you go to the invisible world and try to infuse a block. Then go to your instance folder > TIWorldData and post a list of the file names.

**Comment by JoeSchmo2840** [comment]
World 0
World 1
World -1
World -42

**Comment by TheDrunkMafia** [comment]
I've narrowed the issue down to the fact that Minecraft forces you to watch credits after traveling out of the END. So for now I have disabled travelling between the END and to Overworld.
