### ISSUE TITLE
Teleportation/Motus Server Crash (1.8.9-4.78)

### ISSUE THREAD

**Issue by sdaddy** [TheDrunkMafia/ThaumicInfusion#67]
Server crashes after trying to teleport to new or existing locations. After the server restarts the player is in a new location, but not the coords assigned. 

Crash report: http://pastebin.com/h8h8uq7e

**Comment by sdaddy** [comment]
It seems the problem is only with teleporting to or from the nether. Overworld teleporting works fine.

**Comment by TheDrunkMafia** [comment]
Interesting, I will look into the crash. The fact that the coordinates have been forgotten leads me to believe it's crashing during the checking of if the linked infusion still exists. Which is something I changed when trying to get the End to be compatible.

**Comment by TheDrunkMafia** [comment]
I've released an update on curse forge, it should fix the problem you have been having.
