### ISSUE TITLE
Light from Lux not being removed

### ISSUE THREAD

**Issue by jrpoints** [TheDrunkMafia/ThaumicInfusion#70]
When I shift right-click to remove the lux infusion from a block it removes it visually but the block is still producing light until i break it, a light update doesn't fix it either.

**Comment by TheDrunkMafia** [comment]
Yeah, I know how to fix this. I am forcing the lighting to update when the infusion is first added, however not when it's being removed. It will be fixed in the next version.

**Comment by TheDrunkMafia** [comment]
Fixed in this commit: https://github.com/TheDrunkMafia/ThaumicInfusion/blob/master/src/main/java/drunkmafia/thaumicinfusion/net/packet/server/DataRemovePacketC.java#L79
