### ISSUE TITLE
ThaumicInfusion filling heap with Field objects

### ISSUE THREAD

**Issue by jikuja** [TheDrunkMafia/ThaumicInfusion#72]
Every time ReflectionLookup.findFieldInClass() misses cache getDeclaredFields() is being called which creates Field objects.

* My btrace script: https://paste.ee/p/mdhgB
* Results: https://paste.ee/p/mJijJ

96 % of ReflectionLookup.findFieldInClass() return null. More info in http://forum.feed-the-beast.com/threads/alpha-unstable-pack-bug-reports.42413/page-12#post-1608240

**Comment by TheDrunkMafia** [comment]
Wow, this is really old code. I completely forgot It existed... after looking though it, this code is not useful, even when it actually returns a world object, the invoketion is useless for the block wrapper.

I've fixed this by simply phasing out the use of the reflection handler, I'll be releasing an update soon.

**Comment by TheDrunkMafia** [comment]
Version with fix: http://mods.curse.com/mc-mods/minecraft/220308-thaumic-infusion#

**Comment by jikuja** [comment]
*Was* fixed in ThaumicInfusion-1.8.9-4.83.jar. 
ThaumicInfusion-1.8.9-4.84.jar in curseforge has this problem again.

Btw http://minecraft.curseforge.com/projects/thaumic-infusion/files/2289019 offers file with wrong name.

**Comment by TheDrunkMafia** [comment]
Ah, it would seem I forgot to sync the project between my two computers. It's been fixed now in the latest version
