### ISSUE TITLE
Wand Focus: Infusion - Humanus (Warding)

### ISSUE THREAD

**Issue by PierceSG** [TheDrunkMafia/ThaumicInfusion#73]
Warded blocks and Wither will result in blocks duplication.

The Wither will try to destroy the blocks, and dropping them into the world. But the warded blocks stays in their place.

**Comment by TheDrunkMafia** [comment]
Thanks for reporting this, I will look into this and will release a hotfix soon for it.

**Comment by TheDrunkMafia** [comment]
Do you mind testing this version: http://puu.sh/nQpQQ/4cbeddcf8f.jar to see if the problem has been resolved in your situation?

**Comment by PierceSG** [comment]
Great! That fixes it. That was fast.

Thanks.

**Comment by TheDrunkMafia** [comment]
No problems
