### ISSUE TITLE
Unable to compile source

### ISSUE THREAD

**Issue by bloodmc** [TheDrunkMafia/ThaumicInfusion#76]
https://github.com/TheDrunkMafia/ThaumicInfusion/blob/466beefe37cdb94509b2a691d8642be911cc9842/src/main/java/drunkmafia/thaumicinfusion/common/event/CommonEventContainer.java#L10

IServerTickable is not on Github.

**Comment by TheDrunkMafia** [comment]
Fixed: https://github.com/TheDrunkMafia/ThaumicInfusion/commit/130c3f5105bd12fa79672d8fa85486e175d5ce7d
