### ISSUE TITLE
Conflict with UtilityWorlds mod

### ISSUE THREAD

**Issue by spannerman79** [TheDrunkMafia/ThaumicInfusion#77]
forge 1614
ThaumicInfusion-4.32.jar
UtilityWorlds-1.7.10_1.0.7.jar ( http://minecraft.curseforge.com/projects/utility-worlds )
`Block: zarkov.utilityworlds.UW_PortalBlockhas an issue while merging the changes.`

**Comment by TheDrunkMafia** [comment]
I'm sorry, but I need more to go on than this? I need the FULL crash log and other details about the issue at hand, I have nothing to go on from this.

**Comment by spannerman79** [comment]
https://www.dropbox.com/s/p1rl92f99d59thv/TI_Transformer.log?dl=0

**Comment by TheDrunkMafia** [comment]
I still need an explanation and the crash log please.

**Comment by spannerman79** [comment]
https://paste.ee/p/i4fSk
I don't need to explain that log.....

**Comment by TheDrunkMafia** [comment]
Thaumic Infusion is no longer being supported on version 1.7.10.
