### ISSUE TITLE
auram infusion caused this crash the infused block had a arcane mirror on it

### ISSUE THREAD

**Issue by Phizzhead** [TheDrunkMafia/ThaumicInfusion#79]
https://gist.github.com/Phizzhead/4e5095336496232cd0fcd94153108532

**Comment by TheDrunkMafia** [comment]
I'll release a hotfix shortly to resolve this issue.

**Comment by TheDrunkMafia** [comment]
http://minecraft.curseforge.com/projects/thaumic-infusion/files/2304230
