### ISSUE TITLE
Stacking Issue

### ISSUE THREAD

**Issue by DragonGodGrapha** [TheDrunkMafia/ThaumicInfusion#9]
I don't think it acts like this for the Survival wands and staves, but the Creative staff and wand will stack as the same item for the infusion altar. I doubt this is intended, but I have no clue why this would happen just for the creative wands.

**Comment by TheDrunkMafia** [comment]
Aye, it was not intended. But since the new version of the mod no longer uses an infusion system, instead it uses a Foci, this glitch is no longer in the mod.
